obstacle_range: 12
raytrace_range: 12

transform_tolerance: 5

footprint: [[-0.55, -0.4], [-0.55, 0.4], [0.55, 0.4], [0.55, -0.4]]

plugins:
   - {name: static_map, type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacle_layer:
   observation_sources: laser_scan
   laser_scan: {data_type: LaserScan, topic: /scan, sensor_frame: base_laser, marking: true, clearing: true}
   #sonar_scan: {data_type: PointCloud2, topic: /RosAria/sonar_pointcloud2, sensor_frame: base_link, marking: true, clearing: true, obstacle_range: 0.45, observation_persistence: 2.0}
   track_unknown_space: true
   unkown_cost_value: 0.1
