base_global_planner: global_planner/GlobalPlanner

GlobalPlanner:
  planner_frequency: 15 #30 # 0.6
  planner_patience: 10
  orientation_mode: 2 # interpolate from current orientation to last orientation
