local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 4 #40 #4.0
  publish_frequence: 0.5 #15 # 0.5
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.1 #0.05

  obstacle_layer:
    observation_sources: laser_scan
    laser_scan: {data_type: LaserScan, topic: /scan, sensor_frame: base_laser, marking: true, clearing: true}

  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0
  inflation_layer:
    inflation_radius: 0.3
    cost_scaling_factor: 0.1
